version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./src/main/resources/static
      dockerfile: Dockerfile.front
    container_name: communal-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
